# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
#relative_permalinks: true #removed per https://github.com/poole/lanyon/issues/124#issuecomment-155645090

# Setup
course: CS220
title: "Computer Architecture and Assembly Language"
description: "This course introduces the fundamental physical and structural concepts of assembly language programming. Topics include machine architecture, memory addressing, input/output, interrupts, control structures, compiling, and linking. C-ID COMP-142."
cor: "https://miracosta.curriqunet.com/DynamicReports/AllFieldsReportByEntity/7205?entityType=Course&reportId=329"
logo: "/cs220/assets/images/CS2ZTC.png"
context: "CS220 is part of our CS for Transfer (ADT) degree and Software Development (certificate and associates) degree, often a transfer requirement for a Bachelors in CS, EECS, etc."

last-modified-at:
  date-format: "%m-%d-%Y"
url:
baseurl: /cs220

author:
  name: "Nery Chapeton-Lamas"
  url: https://profe.github.io

plugins:
  - jekyll-paginate
  - jekyll-last-modified-at
paginate: 5
paginate_path: "page:num" #added per https://github.com/poole/lanyon/issues/124#issuecomment-155645090

# Custom vars
themecolor: "theme-base-08"
version: 2.1.0

github:
  repo: https://github.com/MiraCostaCS/cs220
